plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-package-yaml.cjs
    spec: "https://yarn.build/yaml"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.5.0.cjs
